---
- name: SSH Vulnerability Fix
  hosts: all
  tasks:
    - name: Updating Ciphers directive in /etc/ssh/sshd_config file
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Ciphers'
        line: 'Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr'
      become: true

    - name: Updating MACs directive in /etc/ssh/sshd_config file
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MACs'
        line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256'
      become: true

    - name: Updating KexAlgorithms directive in /etc/ssh/sshd_config file
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^KexAlgorithms'
        line: 'KexAlgorithms diffie-hellman-group-exchange-sha256'
        validate: 'sshd -t -f %s'
      become: true

    - name: Restarting sshd service
      service: name=sshd state=restarted
      become: true